import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Postgres",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Using fetch in Next</h1>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/posts">Posts</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
